// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3oxWOx_goyiR4fH1QDNnaDXALIuAgUY',
    appId: '1:468801698747:web:e652a849bb8f94fccaa29e',
    messagingSenderId: '468801698747',
    projectId: 'fuilio',
    authDomain: 'fuilio.firebaseapp.com',
    storageBucket: 'fuilio.firebasestorage.app',
    measurementId: 'G-J0MEN4VWX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZ5kfabanuG1DBJGH-Cx9gyiSvw0iYsM',
    appId: '1:468801698747:android:e4633631b7de912acaa29e',
    messagingSenderId: '468801698747',
    projectId: 'fuilio',
    storageBucket: 'fuilio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPFxuu3dThSWLue7lRX-gCSx4B_BeoDo',
    appId: '1:468801698747:ios:86153f1163186420caa29e',
    messagingSenderId: '468801698747',
    projectId: 'fuilio',
    storageBucket: 'fuilio.firebasestorage.app',
    iosBundleId: 'com.example.fuilioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPFxuu3dThSWLue7lRX-gCSx4B_BeoDo',
    appId: '1:468801698747:ios:86153f1163186420caa29e',
    messagingSenderId: '468801698747',
    projectId: 'fuilio',
    storageBucket: 'fuilio.firebasestorage.app',
    iosBundleId: 'com.example.fuilioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3oxWOx_goyiR4fH1QDNnaDXALIuAgUY',
    appId: '1:468801698747:web:47d2c29d5f207b61caa29e',
    messagingSenderId: '468801698747',
    projectId: 'fuilio',
    authDomain: 'fuilio.firebaseapp.com',
    storageBucket: 'fuilio.firebasestorage.app',
    measurementId: 'G-16XK56CFRB',
  );
}
